export const SET_DISC = 'SET_DISC'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_SHOW_MINI_LIST = 'SET_SHOW_MINI_LIST'

export const SET_SINGER = 'SET_SINGER'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'